In [1]:
#NumPy                      --> Hızlı ve esnek array işlemleri için
#Pandas                     --> Tablo yapısında veri işleme için
#Sci-kit Learn              --> Makine Öğrenmesi Algoritmaları
#Mathplotlib / Seaborn      --> Veri görselleştirme için (Her türlü grafik çizilebilir)

In [9]:
#Numpy   (Hafızadan kazandıran ve hızlı işlemler yapmamızı sağlayan veri yapıları)
a = [1,2,3,4]
b = [11,21,31,41]

a2 = a * 3
print(a2)



[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [14]:
import numpy as np
#Toplu matematik işlemlerini hızlı bir şekilde yapabiliyoruz
numpyA = np.array(a)
numpyB = np.array(b)

ikiKat = numpyA * 2
print(ikiKat)

print(numpyA*numpyB)

[2 4 6 8]
[ 11  42  93 164]


In [15]:
print("Before Reshape")
print(numpyA)
print(numpyA.shape)
numpyA = numpyA.reshape(2,2)
print("After Reshape")
print(numpyA)
print(numpyA.shape)

Before Reshape
[1 2 3 4]
(4,)
After Reshape
[[1 2]
 [3 4]]
(2, 2)


In [16]:
sayilar = np.array(range(100))
print(sayilar)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [19]:
print(sayilar.reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [18]:
print(sayilar.reshape(2,5,10)) # Tensor ( 3 ve daha fazla boyutu olan matris)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [22]:
m1 = np.array(range(0,9))
m1 = m1.reshape(3,3)
print(m1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
m2 = np.array(range(10,19))
m2 = m2.reshape(3,3)
print(m2)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [25]:
m3 = np.matmul(m1,m2)
print(m3)

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]


In [26]:
#Kolay Filtreleme
m3 = m3.reshape(9,)
print(m3)

[ 45  48  51 162 174 186 279 300 321]


In [27]:
buyukSayilar = m3[m3>200]
print(buyukSayilar)

[279 300 321]


In [47]:
points = np.loadtxt('datasets/points.txt',delimiter=',')
print(points.shape)
a = points.reshape(80)
print(a)
print(a[a%2==1])

(40, 2)
[ 5.  5. 15. 17. 15. 16.  5.  6.  6.  6. 16. 16.  8.  8.  7.  6. 17. 17.
  6.  7.  7.  8. 18. 18.  8.  6. 17. 16.  5.  8. 17. 16.  8.  8. 16. 17.
 17. 18. 18. 16.  5. 15. 15.  7. 15.  6.  5. 16.  6. 16. 16.  6.  8. 18.
  7. 16. 17.  7.  6.  7.  7.  8. 18.  8.  8. 16. 17.  6.  5. 18. 17.  6.
  8. 18. 16.  7. 17.  8. 18.  6.]
[ 5.  5. 15. 17. 15.  5.  7. 17. 17.  7.  7. 17.  5. 17. 17. 17.  5. 15.
 15.  7. 15.  5.  7. 17.  7.  7.  7. 17.  5. 17.  7. 17.]


In [46]:
a%2==1

array([ True,  True,  True,  True,  True, False,  True, False, False,
       False, False, False, False, False,  True, False,  True,  True,
       False,  True,  True, False, False, False, False, False,  True,
       False,  True, False,  True, False, False, False, False,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False,  True,  True, False,  True,  True, False, False,
       False, False, False,  True, False,  True, False,  True, False,
       False, False, False,  True,  True, False, False, False])

In [39]:
#Advanced Indexing & Fancy indexing
f = np.array([11,22,33])
g = f[[False,False,True]]
print(g)
print(f)

[33]
[11 22 33]


In [50]:
r = np.arange(0,200,2)
r = r.reshape(10,10)
print(r)

[[  0   2   4   6   8  10  12  14  16  18]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 60  62  64  66  68  70  72  74  76  78]
 [ 80  82  84  86  88  90  92  94  96  98]
 [100 102 104 106 108 110 112 114 116 118]
 [120 122 124 126 128 130 132 134 136 138]
 [140 142 144 146 148 150 152 154 156 158]
 [160 162 164 166 168 170 172 174 176 178]
 [180 182 184 186 188 190 192 194 196 198]]


In [53]:
print(r[0,:])

[ 0  2  4  6  8 10 12 14 16 18]


In [54]:
print(r[1,:])

[20 22 24 26 28 30 32 34 36 38]


In [57]:
print(r[:,2])

[  4  24  44  64  84 104 124 144 164 184]


In [58]:
print(r[:,0::2])

[[  0   4   8  12  16]
 [ 20  24  28  32  36]
 [ 40  44  48  52  56]
 [ 60  64  68  72  76]
 [ 80  84  88  92  96]
 [100 104 108 112 116]
 [120 124 128 132 136]
 [140 144 148 152 156]
 [160 164 168 172 176]
 [180 184 188 192 196]]


In [60]:
print(r[1,][::-1])

[38 36 34 32 30 28 26 24 22 20]


In [61]:
a = np.array([1,2,3,4,5])
print(a)
print(a[::-1]) #Reverse array

[1 2 3 4 5]
[5 4 3 2 1]


In [66]:
g = np.array([12,12,43,54,56,54,3,23,2,32,3,23,2,33,23,23])
print(g.max())
print(g.min())
print(g.mean())
print(g.std())

56
2
24.875
18.472530281474707


In [90]:
world = np.loadtxt('datasets/world.txt',delimiter=',',dtype='str')
a1 = world[world[:,1]=='Europe']   #Önce ikinci kolon ( birinci index) teki değeri 'Europe' olanları seçiyoruz
a2 = a1[:,-1]                      #Sonra seçilen Avrupa ülkelerinin sacece son kolonu( nüfus bilgisi) alıyoruz
a3 = a2.astype('int')              #Daha sonra string değerleri int (tamsayı ya) döüştürüyoruz
toplam = a3.sum()                  #En son tüm elemanları topluyoruz
print("Avrupanın nüfusu : ",toplam)   

662292883


In [91]:
print("Asya nüfus", world[world[:,1]=='Asia'][:,-1].astype('int').sum()   )

Asya nüfus 3982554409


In [93]:
print("Okyanusya nüfus", world[world[:,1]=='Oceana'][:,-1].astype('int').sum()   )

Okyanusya nüfus 32018861


In [96]:
print("Kuzey Amerika nüfus", world[world[:,1]=='North America'][:,-1].astype('int').sum()   )

Kuzey Amerika nüfus 511265886
